# Generated by Django 5.2 on 2025-04-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_course_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-rating'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
    ]
